
let err = error 'hi'

abort(err)

writeline('bye')
